### ISSUE TITLE
Expecting Soul swap on MIND Smart Chain 

### ISSUE THREAD

**Issue by nnlgsakib** [SoulSwapFinance/soul-interface#1455]
Dear SoulSwap Team,

I am Sakib, Chief Developer at Mind Smart Chain. We are considering the deployment of SoulSwap on our network. Is Soul Swap interested in exploring this collaboration?

For more details, please visit our website at mindchain.com or explore our mainnet at mainnet.mindscan.info.

Thank you for your consideration.

Best regards,
Sakib

**Comment by BunsDev** [comment]
Greetings, we are not expanding to another network in the immediate future and doing so would require a governance proposal with majority support. I recommend bringing this up in our forums, if you would like to communicate this opportunity with our community.
