### ISSUE TITLE
Hitting "max" when trying to unstake doesn't always work 

### ISSUE THREAD

**Issue by Gahen** [SoulSwapFinance/soul-interface#417]
**Bug Description**
Seems likely to be happening when having more seance than soul staked and hitting "max" doesn't sets the right number to unstake.

**Steps to Reproduce**
1. Go to /seance
2. Click on withdraw tab and "max"
3. Try to click the withdraw button

**Expected Behavior**
It should work or be clear about the reason it's not working

**Comment by BunsDev** [comment]
The reason for this is the pop-up doesn't work with the current modal configurations, but I will get to work on it.

**Comment by BunsDev** [comment]
fixed <3
