### ISSUE TITLE
All pages should load correctly or show an accurate error when something is off

### ISSUE THREAD

**Issue by Gahen** [SoulSwapFinance/soul-interface#432]
**Bug Description**
There are a few pages that are showing confusing errors when it should be possible to be more accurate. I wanted to create this ticket so I don't forget to fix this, I'll add more pages to improve soon and will try to fix them after that.

**List of pages + conditions with useless errors**

- [ ] [mines when connected to ethereum](https://exchange.soulswap.finance/es-AR/mines?filter=active)
- [ ] [TBD](#)
...

**Expected Behavior**
The errors should be helpful or the page should not fail at all.

**Additional Context**
I'll update this tomorrow, feel free to assign it to me =P

**Comment by BunsDev** [comment]
<b>Fixed, tysm! <3 </b>

<img width="607" alt="Screen Shot 2022-02-21 at 4 37 33 PM" src="https://user-images.githubusercontent.com/68980965/155034113-304c4c87-c035-45bf-9bc4-1736f6b3560d.png">

**Comment by BunsDev** [comment]
<img width="524" alt="Screen Shot 2022-02-21 at 4 42 22 PM" src="https://user-images.githubusercontent.com/68980965/155034525-240f84af-f3c4-4cdf-ab17-2eced27759c1.png">

**Comment by BunsDev** [comment]
<H1>Bonds Page</H1>
<img width="541" alt="Screen Shot 2022-02-21 at 4 44 01 PM" src="https://user-images.githubusercontent.com/68980965/155034636-e096e587-95b1-45e1-a57d-b8daf31895da.png">
